### ISSUE TITLE
The example does not work.

### ISSUE THREAD

**Issue by seekstar** [bhuztez/porus#19]
```shell
./c.py submit solutions/judge.u-aizu.ac.jp/ITP1/ITP1_1_A.rs
```
```
[ !! ] .1.1.1 Compile porus                                                                                                                                                                          
[ !! ] .1.1 Compile /home/searchstar/git/others/porus/solutions/judge.u-aizu.ac.jp/ITP1/ITP1_1_A.rs                                                                                                  
[ !! ] .1 Read submission code of solutions/judge.u-aizu.ac.jp/ITP1/ITP1_1_A.rs                                                                                                                      
[ !! ] Submit                                                                                                                                                                                        
Traceback (most recent call last):
  File "./c.py", line 14, in <module>
    main("Porus Project")
  File "/home/searchstar/.local/lib/python3.8/site-packages/wronganswer/project.py", line 353, in main
    main(argv)
  File "/home/searchstar/.local/lib/python3.8/site-packages/wronganswer/command.py", line 115, in __call__
    return cmd(args)
  File "/home/searchstar/.local/lib/python3.8/site-packages/wronganswer/command.py", line 67, in wrapper
    return func(**{d:getattr(args, d) for d in dests if getattr(args, d) is not None})
  File "/home/searchstar/.local/lib/python3.8/site-packages/wronganswer/task.py", line 44, in wrapper
    raise e
subprocess.CalledProcessError: Command '/home/searchstar/.cargo/bin/xargo rustc --lib -q --release --target x86_64-unknown-linux-gnu --features online-judge --message-format json' returned non-zero exit status 101.
```

I tried to run ```/home/searchstar/.cargo/bin/xargo rustc --lib -q --release --target x86_64-unknown-linux-gnu --features online-judge --message-format json``` directly in the root of the repository, and the output is as follows:
```
{"reason":"compiler-artifact","package_id":"proc-macro2 1.0.24 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["custom-build"],"crate_types":["bin"],"name":"build-script-build","src_path":"/home/searchstar/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.24/build.rs","edition":"2018","doc":false,"doctest":false,"test":false},"profile":{"opt_level":"0","debuginfo":null,"debug_assertions":false,"overflow_checks":false,"test":false},"features":["default","proc-macro"],"filenames":["/home/searchstar/git/others/porus/target/release/build/proc-macro2-705efb4cfe435430/build-script-build"],"executable":null,"fresh":true}
{"reason":"compiler-artifact","package_id":"unicode-xid 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"crate_types":["lib"],"name":"unicode-xid","src_path":"/home/searchstar/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-xid-0.2.1/src/lib.rs","edition":"2015","doc":true,"doctest":true,"test":true},"profile":{"opt_level":"0","debuginfo":null,"debug_assertions":false,"overflow_checks":false,"test":false},"features":["default"],"filenames":["/home/searchstar/git/others/porus/target/release/deps/libunicode_xid-e49ccfcd96bc85d1.rlib","/home/searchstar/git/others/porus/target/release/deps/libunicode_xid-e49ccfcd96bc85d1.rmeta"],"executable":null,"fresh":true}
{"reason":"compiler-artifact","package_id":"syn 1.0.56 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["custom-build"],"crate_types":["bin"],"name":"build-script-build","src_path":"/home/searchstar/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.56/build.rs","edition":"2018","doc":false,"doctest":false,"test":false},"profile":{"opt_level":"0","debuginfo":null,"debug_assertions":false,"overflow_checks":false,"test":false},"features":["clone-impls","default","derive","full","parsing","printing","proc-macro","quote"],"filenames":["/home/searchstar/git/others/porus/target/release/build/syn-1ebbea6b38f7501f/build-script-build"],"executable":null,"fresh":true}
{"reason":"build-script-executed","package_id":"proc-macro2 1.0.24 (registry+https://github.com/rust-lang/crates.io-index)","linked_libs":[],"linked_paths":[],"cfgs":["lexerror_display","hygiene","use_proc_macro","wrap_proc_macro","proc_macro_span"],"env":[],"out_dir":"/home/searchstar/git/others/porus/target/release/build/proc-macro2-99e94f13672d70a2/out"}
{"reason":"build-script-executed","package_id":"syn 1.0.56 (registry+https://github.com/rust-lang/crates.io-index)","linked_libs":[],"linked_paths":[],"cfgs":[],"env":[],"out_dir":"/home/searchstar/git/others/porus/target/release/build/syn-2fabc0bda437a215/out"}
{"reason":"compiler-artifact","package_id":"proc-macro2 1.0.24 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"crate_types":["lib"],"name":"proc-macro2","src_path":"/home/searchstar/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.24/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},"profile":{"opt_level":"0","debuginfo":null,"debug_assertions":false,"overflow_checks":false,"test":false},"features":["default","proc-macro"],"filenames":["/home/searchstar/git/others/porus/target/release/deps/libproc_macro2-da572b0555faaa37.rlib","/home/searchstar/git/others/porus/target/release/deps/libproc_macro2-da572b0555faaa37.rmeta"],"executable":null,"fresh":true}
{"reason":"compiler-artifact","package_id":"quote 1.0.8 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"crate_types":["lib"],"name":"quote","src_path":"/home/searchstar/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.8/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},"profile":{"opt_level":"0","debuginfo":null,"debug_assertions":false,"overflow_checks":false,"test":false},"features":["default","proc-macro"],"filenames":["/home/searchstar/git/others/porus/target/release/deps/libquote-474c06fa394e039b.rlib","/home/searchstar/git/others/porus/target/release/deps/libquote-474c06fa394e039b.rmeta"],"executable":null,"fresh":true}
{"reason":"compiler-artifact","package_id":"syn 1.0.56 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"crate_types":["lib"],"name":"syn","src_path":"/home/searchstar/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.56/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},"profile":{"opt_level":"0","debuginfo":null,"debug_assertions":false,"overflow_checks":false,"test":false},"features":["clone-impls","default","derive","full","parsing","printing","proc-macro","quote"],"filenames":["/home/searchstar/git/others/porus/target/release/deps/libsyn-207dba37273afa3f.rlib","/home/searchstar/git/others/porus/target/release/deps/libsyn-207dba37273afa3f.rmeta"],"executable":null,"fresh":true}
{"reason":"compiler-message","package_id":"porus_macros 0.0.0 (path+file:///home/searchstar/git/others/porus/porus_macros)","target":{"kind":["proc-macro"],"crate_types":["proc-macro"],"name":"porus_macros","src_path":"/home/searchstar/git/others/porus/porus_macros/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},"message":{"rendered":"error[E0463]: can't find crate for `rustc_parse_format`\n  --> porus_macros/lib.rs:23:1\n   |\n23 | extern crate rustc_parse_format;\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate\n\n","children":[],"code":{"code":"E0463","explanation":"A plugin/crate was declared but cannot be found.\n\nErroneous code example:\n\n```compile_fail,E0463\n#![feature(plugin)]\n#![plugin(cookie_monster)] // error: can't find crate for `cookie_monster`\nextern crate cake_is_a_lie; // error: can't find crate for `cake_is_a_lie`\n```\n\nYou need to link your code to the relevant crate in order to be able to use it\n(through Cargo or the `-L` option of rustc example). Plugins are crates as\nwell, and you link to them the same way.\n"},"level":"error","message":"can't find crate for `rustc_parse_format`","spans":[{"byte_end":641,"byte_start":609,"column_end":33,"column_start":1,"expansion":null,"file_name":"porus_macros/lib.rs","is_primary":true,"label":"can't find crate","line_end":23,"line_start":23,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":33,"highlight_start":1,"text":"extern crate rustc_parse_format;"}]}]}}
{"reason":"compiler-message","package_id":"porus_macros 0.0.0 (path+file:///home/searchstar/git/others/porus/porus_macros)","target":{"kind":["proc-macro"],"crate_types":["proc-macro"],"name":"porus_macros","src_path":"/home/searchstar/git/others/porus/porus_macros/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},"message":{"rendered":"error: aborting due to previous error\n\n","children":[],"code":null,"level":"error","message":"aborting due to previous error","spans":[]}}
{"reason":"compiler-message","package_id":"porus_macros 0.0.0 (path+file:///home/searchstar/git/others/porus/porus_macros)","target":{"kind":["proc-macro"],"crate_types":["proc-macro"],"name":"porus_macros","src_path":"/home/searchstar/git/others/porus/porus_macros/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},"message":{"rendered":"For more information about this error, try `rustc --explain E0463`.\n","children":[],"code":null,"level":"failure-note","message":"For more information about this error, try `rustc --explain E0463`.","spans":[]}}
{"reason":"build-finished","success":false}
error: could not compile `porus_macros`

To learn more, run the command again with --verbose.
```

All requirements have been installed:
```shell
pip3 install --user -r requirements.txt
```
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: wronganswer>=0.1.7 in /home/searchstar/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.1.7)
Requirement already satisfied: html5lib in /usr/lib/python3.8/site-packages (from wronganswer>=0.1.7->-r requirements.txt (line 1)) (1.1)
Requirement already satisfied: six>=1.9 in /usr/lib/python3.8/site-packages (from html5lib->wronganswer>=0.1.7->-r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: webencodings in /usr/lib/python3.8/site-packages (from html5lib->wronganswer>=0.1.7->-r requirements.txt (line 1)) (0.5.1)
```

The version of rustc: ```rustc 1.51.0-nightly (158f8d034 2020-12-29)```
The version of xargo and cargo:
```
xargo 0.3.22
cargo 1.50.0-nightly (75d5d8cff 2020-12-22)
```
The version of python: ```Python 3.8.6```
The version of Linux: ```5.9.11-3-MANJARO```

**Comment by bhuztez** [comment]
```
rust component add rustc-dev rust-src
```
