### ISSUE TITLE
Are there any restrictions about the location of the input rust file?

### ISSUE THREAD

**Issue by seekstar** [bhuztez/porus#23]
```rs
fn main() {
    let mut n = default();
    scanf!("{:usize}", &mut n);
    printf!("{:usize}\n", n);
}
```

If I place this file in `porus/test.rs` and run `./c.py preview test.rs`, an error will occur:

```text
[ !! ] Preview submission of test.rs                                                                                
Traceback (most recent call last):
  File "/home/searchstar/git/others/porus/./c.py", line 14, in <module>
    main("Porus Project")
  File "/home/searchstar/.local/lib/python3.10/site-packages/wronganswer/project.py", line 356, in main
    main(argv)
  File "/home/searchstar/.local/lib/python3.10/site-packages/wronganswer/command.py", line 123, in __call__
    return cmd(args)
  File "/home/searchstar/.local/lib/python3.10/site-packages/wronganswer/command.py", line 67, in wrapper
    return func(**{d:getattr(args, d) for d in dests if getattr(args, d) is not None})
  File "/home/searchstar/.local/lib/python3.10/site-packages/wronganswer/task.py", line 43, in wrapper
    raise e.with_traceback(None)
TypeError: cannot unpack non-iterable NoneType object
```

However, it compiles:

```text
$ ./c.py compile test.rs
[ OK ] .1 Compile porus                                                                                             
[ OK ] Compile test.rs
```

But if I place it in `examples/judge.u-aizu.ac.jp/ITP1/test.rs`, then everything is fine: `./c.py preview examples/judge.u-aizu.ac.jp/ITP1/test.rs`

```text
[ OK ] .1.1.1 Compile porus                                                                                         
[ OK ] .1.1 Compile /home/searchstar/git/others/porus/examples/judge.u-aizu.ac.jp/ITP1/test.rs                      
[ OK ] .1.2 Read source of /home/searchstar/git/others/porus/examples/judge.u-aizu.ac.jp/ITP1/target/x86_64-unknown-
[ OK ] .1 Read submission code of examples/judge.u-aizu.ac.jp/ITP1/test.rs                                          
#define _ "rust_eh_personality"
#define a "\",@progbits"
#define b "xorl\t%eax, %eax\n\t"
#define d ",@object\n\t.section\t.rodata"
#define c ":\n\t.asciz\t\"%zu"
__asm__("\t.text\n\t.file\t\"rust_out.c682e2b6-cgu.0\"\n\t.section\t.text.main,\"ax"a"\n\t.globl\tmain\n\t.p2align\t4, 0x90\n\t.type\tmain,@function\nmain:\n\tpushq\t%rax\n\tmovq\t$0, (%rsp)\n\tleaq\t.L._(%rip), %rdi\n\tmovq\t%rsp, %rsi\n\t"b"callq\t*scanf@GOTPCREL(%rip)\n\tmovq\t(%rsp), %rsi\n\tleaq\t.L_(%rip), %rdi\n\t"b"callq\t*printf@GOTPCREL(%rip)\n\t"b"popq\t%rcx\n\tretq\n.L0_:\n\t.size\tmain, .L0_-main\n\n\t.section\t.text."_",\"ax"a"\n\t.globl\t"_"\n\t.p2align\t4, 0x90\n\t.type\t"_",@function\n"_":\n\tretq\n.L1_:\n\t.size\t"_", .L1_-"_"\n\n\t.type\t.L._"d".cst4,\"aM"a",4\n.L._"c"\"\n\t.size\t.L._, 4\n\n\t.type\t.L_"d"..L_,\"a"a"\n.L_"c"\\n\"\n\t.size\t.L_, 5\n\n\t.section\t\".note.GNU-stack\",\""a"\n");
[ OK ] Preview submission of examples/judge.u-aizu.ac.jp/ITP1/test.rs
```

That's confusing.

**Comment by seekstar** [comment]
I see. Thank you very much!
